name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open Cargo.toml
        2. Type '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: manifest
    attributes:
      label: Manifest File
      description: Relevant part of your Cargo.toml (or other manifest)
      render: toml

  - type: dropdown
    id: editor
    attributes:
      label: Editor
      options:
        - Zed
        - Neovim
        - Helix
        - VS Code
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: deps-lsp Version
      description: Output of deps-lsp --version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (if available)
      render: shell
